version: '3'

services:
    
    backend:
        build: ./metatris-backend/
        ports:
            - 4000:4000
        container_name: backend-app
    frontend:
        build: ./metatris-frontend/
        ports:
        - 3000:3000
        container_name: frontend-app